### ISSUE TITLE
margin, padding

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [MorganaLF/resume#10]
Убрать у блоков margin, padding

**Comment by MorganaLF** [comment]
А если у меня есть один общий блок wrapper и он центрируется на странице с помощью `margin: 0 auto`, то вокруг него тоже нужно создавать дополнительный блок, который его будет центрировать, и переносить margin туда?

**Comment by alextsk** [comment]
есть body, можно в нем центрировать. или wrapper развернуть на все поле и создать в нем элемент с маржином. 
вообще по бэм паддинг внутри блока не запрещен, так что можно и  wrapper дать паддинг

**Comment by MorganaLF** [comment]
@GoodDayTodayOkey ишью можно закрывать?

**Comment by GoodDayTodayOkey** [comment]
Да все круто)
