### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/resume#11]
не нужно лишних обобщений в именах типа container
в нем есть смысл если внутри лежит лежит элемент того же блока и нужно ему дать окружение: .block__menu-container .block__menu

https://github.com/MorganaLF/resume/blob/2bd3dbe5885cead1c0dbdd4808b449e20e61fab3/src/components/wrapper/wrapper.pug#L11

здесь можно обойтись просто wrapper__blocks 

https://github.com/MorganaLF/resume/blob/2bd3dbe5885cead1c0dbdd4808b449e20e61fab3/src/components/education/education.pug#L7

https://github.com/MorganaLF/resume/blob/2bd3dbe5885cead1c0dbdd4808b449e20e61fab3/src/components/skills/skills.pug#L7
здесь другая проблема - получается что skills знает что именно в нем лежит, а не должен, он только предоставляет коробку. c education то же самое. может еще где, посмотри по проекту

**Comment by alextsk** [comment]
subtitle-group тоже странное имя, пришлось зайти в файл, чтобы понять что это просто заголовок

**Comment by alextsk** [comment]
unordered-list - это просто тег ul, очень общее, есть же какая то семантическая связь между этими списками, кроме того что они списки)

**Comment by MorganaLF** [comment]
> здесь другая проблема - получается что skills знает что именно в нем лежит, а не должен, он только предоставляет коробку. c education то же самое. может еще где, посмотри по проекту

Тут я делала по примеру, который дается на Риззоме:

![123](https://user-images.githubusercontent.com/38564412/56945959-89253f80-6b31-11e9-9eb8-4f6e98aea870.png)

Кстати, в новых стандартах этот момент никак не обговаривается, есть ли какие-то соглашения по этому поводу?

**Comment by alextsk** [comment]
> есть ли какие-то соглашения по этому поводу

скорее всего нет, именования вообще такая трудно кодифицируемая область. 
основной принцип разделения на блоки - это индивидуальное переиспользование. т.е. если компонент сам по себе имеет смысл - это блок. задача - получить возможность легко заменять содержимое не трогая контейнеры, но это не точная наука, тут нужно делать предположения что может быть заменяемым, а что без контекста не живет.

по container - как я выше написал - они иногда могуть быть, когда это нужно чтобы понять - вот элемент а вот его личный контейнер, но когда все подряд контейнеры они просто визуально замусоривают код.

в скиллс я думаю  есть три блока - это 1 залоговок плюс контейнер для содержимого, это 2 список элементов с заголовками и это 3 виджет с точками

**Comment by MorganaLF** [comment]
Но для позиционирования одного блока внутри другого блока нужны контейнеры, или это как-то по-другому делается? С учетом того, что миксы использовать не допускается.

**Comment by alextsk** [comment]
нужны конечно,  почти все элементы блоков верхнего уровня контейнеры, просто необязательно их все называть *-container

**Comment by alextsk** [comment]
unorderedListOptions - имя такое общее имя, там же конкретные данные лежат

**Comment by MorganaLF** [comment]
Исправлено.
