### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by alextsk** [MorganaLF/resume#16]
https://github.com/MorganaLF/resume/blob/f28108c75eb548cea329ed85c2459469be81c1fd/src/components/personal-data/personal-data.pug#L4

здесь из внешних данных задается относительный путь к картинке, получается внешний блок знает особенности строения внутреннего блока.
и что важнее - эта картинка не часть блока, так он очень уж специализированный получается, хотелось бы иметь возможность менять фотографии)

в sectionheader тоже можно сделать картинки внешним содержимым. но если считаешь что они часть блока, то тут можно зачесть, просто сделать им свою папку, и не интерполируй имена прямо в класс, привязывайся к конфигу типа: {skills: './images/skillls.v2.4.5.jpg'}

**Comment by alextsk** [comment]
и отдельная просьба, можешь в ишью что нибудь отписывать когда закрываешь? когда просто ставишь метку уведомления не приходят

**Comment by MorganaLF** [comment]
Перенесла картинки в папку images. 
Только вот этот момент не поняла: 

> здесь из внешних данных задается относительный путь к картинке, получается внешний блок знает особенности строения внутреннего блока.

Здесь ведь указывается путь в папке dist, и он не связан с внутренним устройством блока.

**Comment by alextsk** [comment]
>  ведь указывается путь в папке dist

это детали сборки, семантически важно что в блоке хранится ресурс к которому он прямого доступа не имеет, только через аргументы, которые ему передал вызывающий блок. т.е. эта картинка могла в соседнем блоке лежать или на другом сайте. такие ресурсы лучше помещать в общие для всех блоков папки, рядом со шрифтами, так и логичнее и понятнее структура проекта, не все хотят читать конфиги сборщика)

**Comment by alextsk** [comment]
кстати, в плагине вроде есть глоб паттерны, чтото такое может сократить код `from: './src/**/*.(jpg|png)'`

**Comment by alextsk** [comment]
https://github.com/MorganaLF/resume/blob/01ac0a9990ec96ccf7c76c049a59258a5e086f8c/src/components/section-header/section-header.pug#L4

это все еще надо поправить, компонент должен иметь конечный набор состояний.
если передать несуществующий icon он должен отрендерить какое-то дефолтное состояние, но для этого все известные варианты icon должны быть объявлены заранее, см выше про конфиг

**Comment by MorganaLF** [comment]
Сначала сделала просто массив с модификаторами иконок, потом вспомнила про

>  не интерполируй имена прямо в класс, привязывайся к конфигу типа: {skills: './images/skillls.v2.4.5.jpg'}

Как это должно выглядеть? Если я передаю в конфиге url, то никак его в css не передам, получается, мне надо инлайн-стили задавать для иконок, а не через модификаторы стилизовать?

**Comment by alextsk** [comment]
если урл то можно инлайн, но конфиг с урлами как пример, главное не брать куски классов напрямую из внешних данных, 
твой вариант рабочий, но все еще привязан к именам в параметрах, мне кажется тут лучше будет хешмап
icons = {"arg1": "element1", ...} 
....
class=`section-header__icon-${icons[icon] || "defaultElement"}` 

кстати, можно передавать данные в css если очень нужно, через css variables

**Comment by MorganaLF** [comment]
Надеюсь, я правильно поняла, что нужно было сделать)

**Comment by alextsk** [comment]
да, все так, только присваивание не нужно, icons же const) не надо его менять

**Comment by MorganaLF** [comment]
Точно)
