### ISSUE TITLE
Оформление стилей

### ISSUE THREAD

**Issue by Frolikow** [MorganaLF/resume#2]
Между стилями блоков, элементов, модификаторов лучше оставлять пустую строку. Будет легче читаться. Пример для сравнения: 
![image](https://user-images.githubusercontent.com/25764783/56430855-ef1ff480-62f1-11e9-8417-60e35639a305.png)

**Comment by Frolikow** [comment]
Еще маленько осталось до общего стиля

**Comment by MorganaLF** [comment]
![mixin](https://user-images.githubusercontent.com/38564412/56499757-72b72c80-6510-11e9-8508-d2493dbd9877.png)
А в таком случае перед миксином тоже пустая строка нужна? Или только перед миксинами медиазапросов?

**Comment by Frolikow** [comment]
В таком случае читается и выглядит нормально, а миксин медиазапросов содержит свои правила, со своим(бо'льшим) отступом. Поэтому там лучше добавить отступ
