### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Frolikow** [MorganaLF/resume#3]
Тут у тебя, во-первых определяется блок внутри блока. И стили от вложенного блока не пойми где лежат(хотя должны лежать в одной директории с этим блоком)
Во-вторых, из-за этого блока - примеси, которые крайне не желательны. Там стилей 2-3 строчки, поэтому не вижу смысла выносить их в отдельный класс.
В-третьих, на span'е у тебя просто модификатор висит. Сам по себе модификатор существовать не может, он должен Что-то модифицировать.
![image](https://user-images.githubusercontent.com/25764783/56430947-4e7e0480-62f2-11e9-965b-653ac76719dc.png)

**Comment by Frolikow** [comment]
Сейчас другая ошибка появилась, если посмотреть на этот код:
![image](https://user-images.githubusercontent.com/25764783/56499587-2e885400-6531-11e9-9f97-214bc84e8d57.png)
Если я захочу задать стили элементу `profile__text`, то к какому элементу они применятся?) Надеюсь понимаешь про что я?)

**Comment by MorganaLF** [comment]
То есть, получается, что это должны быть два разных элемента блока, например, `p.profile__text` и `span.profile__bold-text`? 
Что-то я не пойму, как сделать так, чтобы он перестал быть похожим на модификатор)

**Comment by Frolikow** [comment]
Да, это ведь по факту два разных элемента) можно назвать, как-нибудь вроде profile__text profile__important-text? или мб придумаешь лучше)

**Comment by Frolikow** [comment]
Еще нашел схожую ошибку:
  ```pug
        .progress-bar__indicator-container.progress-bar__indicator-container_solid
            .progress-bar__indicator_solid.progress-bar__indicator_full(style=`width:${completedProgress}%`)
```
