### ISSUE TITLE
Именование модификаторов

### ISSUE THREAD

**Issue by Frolikow** [MorganaLF/resume#6]
Не сразу понятно что означают эти модификаторы:
![image](https://user-images.githubusercontent.com/25764783/56431774-378ce180-62f5-11e9-9a13-931d6ef2cd3d.png)
Можешь объяснить, почему именно так решила назвать?

**Comment by MorganaLF** [comment]
Это  имелось ввиду, что сетка поделена на 10 частей, одна колонка 4 части занимает, а другая 6. Но сейчас понимаю, что вообще обычно на 12 частей принято делить и в целом такое именование не очевидно. А если _big и _small модификаторы сделать, так лучше?

**Comment by Frolikow** [comment]
> А если _big и _small модификаторы сделать, так лучше?

Мне кажется, что больше подойдет left/right.
