### ISSUE TITLE
px to rem

### ISSUE THREAD

**Issue by Frolikow** [MorganaLF/resume#7]
Объясни почему решила переводить пиксели переводить таким способом
![image](https://user-images.githubusercontent.com/25764783/56432844-1c23d580-62f9-11e9-926e-02660a8109e1.png)
а не так 
![image](https://user-images.githubusercontent.com/25764783/56432910-4aa1b080-62f9-11e9-8ea8-95273189d600.png) ?

**Comment by MorganaLF** [comment]
Ну, мне показалось, что в пикселях нагляднее, чем в rem, особенно, когда при переводе в rem получается много знаков после запятой. На макете все в пикселях и в css-файле в пикселях, сразу видно, где, что. Ну и плюс вручную считать rem-ы слишком долго, а так все само считается.

**Comment by Frolikow** [comment]
А мне кажется, что это лишняя логика. То что `при переводе в rem получается много знаков после запятой`, тебя не должно смущать, это не проблема. 
А `сразу видно, где, что.` и `вручную считать rem-ы слишком долго` - решается расширением "px-to-rem". Ставишь курсор на нужном значении и нажимаешь Alt+Z и все) можно выделить фрагмент кода или весь код и сразу все заменить) тратится при этом минимум времени)

**Comment by MorganaLF** [comment]
А вот про расширение не знала, хорошо, переделаю)

**Comment by alextsk** [comment]
в исходниках можно хранить в пикселях, если при сборке переводится в рем

**Comment by MorganaLF** [comment]
Ну да, после сборки в css-файле все в rem-ах. 
@Frolikow, @alextsk так можно не переделывать, оставить как есть?

**Comment by alextsk** [comment]
лучше убрать свою функцию из сасс и прикрутить какой нибудь плагин для вебпака, который будет этим заниматься. логически это все же часть сборки
